name: Linkcheck

on:
  schedule:
    - cron: '11 11 * * 1'

jobs:
  build:
    name: Linkcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: python -m pip install '.[doc]'

      - name: Run linkcheck
        run: make linkcheck
